drop table teams;
drop table players;
drop table player_regular_season;
drop table player_regular_season_career;
drop table player_playoffs;
drop table player_playoffs_career;
drop table coaches_season;
drop table coaches_career;
drop view view1;
drop view view2;
drop view eff players;
drop view regular_seasons;
drop view playoffs;